language: generic
matrix:
  include:
    - os: osx
      osx_image: xcode10.1

before_install:
  - brew tap vapor/tap
  - brew update
  - brew install vapor

services:
  - docker

env:
  - COMPOSE_FILE=docker-compose.yml:docker-compose.override.travis.yml
  
script:
  # run unit tests
  - docker-compose build
  - docker-compose up --abort-on-container-exit

after_success:
  - bash <(curl -s https://codecov.io/bash)