machine:
  xcode:
    version: "10.1"

dependencies:
  pre:
    - brew install postgres
    - brew install vapor/tap/vapor
    - swift package fetch
  cache_directories:
    - "./.build"

compile:
  override:
    - vapor build

test:
  override:
    - set -o pipefail &&
      swift test 2>&1 |
      tee $CIRCLE_ARTIFACTS/test.log |
      xcpretty --color --report junit --output $CIRCLE_TEST_REPORTS/results.xml

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: develop
