# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Legere-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Legere-iOS
    pod 'SwifterSwift'
    pod 'Moya/RxSwift'
    pod 'RxDataSources'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'SimpleTwoWayBinding'

  target 'Legere-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Legere-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
